on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

name: continuous-integration

defaults:
  run:
    shell: nu {0}

env:
  NU_LOG_LEVEL: DEBUG

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hustcer/setup-nu@v3.10
        with:
          version: nightly

      - name: Show Nushell Version
        run: version

      - name: Run the tests
        run: make test
